# Generated by Django 5.0.7 on 2025-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_product_img_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
