# Generated by Django 5.0.7 on 2025-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0005_alter_orderdetail_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("Stripe", "Stripe")], max_length=10
            ),
        ),
    ]
